admin/admin_dashboard/urls.py
from django.urls import path

from .views import *

app_name = "admin_dashboard"

urlpatterns = [
    path('', LogIn, name="login"),
    path('logout/', logout_user, name="logout_user"),
    path('dashboard/', dashboard, name="dashboard"),
    path('users/', users_listing, name="all_users"),
    path('users/<int:id>/<str:mode>/', add_update_user, name="user_view_edit"),
    path('users/delete/<int:id>/', delete_user, name="delete_user")
]

admin/admin_panel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

admin.site.site_header = 'Zukti Inovations'
admin.site.site_title = 'Zukti Inovations'
admin.site.site_url = "/admin/dashboard"
admin.site.index_title = 'Zukti Inovations'
admin.empty_value_display = '**Empty**'

urlpatterns = [
    path('backend/', admin.site.urls),
    path("admin/", include("admin_dashboard.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += (
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    )

admin/admin_dashboard/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .manager import UserManager


# Create your models here.

class Users(AbstractUser):

    username = None
    email = models.EmailField("email address", blank=True,unique=True)
    social_id = models.CharField(max_length=500, null=True, blank=True)
    login_type = models.CharField(default="normal", max_length=255, choices=(
        ("normal", "Normal"), ("google", "Google"), ("facebook", "Facebook")
    ))
    is_one_time_login = models.BooleanField(default=False)
    is_pd_distance = models.BooleanField(default=False)
    is_reading_distance = models.BooleanField(default=False)
    is_f_meter = models.BooleanField(default=False)
    objects = UserManager()
    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["first_name", "last_name"]
    image = models.ImageField(null=True, blank=True)

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

admin/admin_dashboard/views.py
import random
import string
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import user_passes_test
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse

User = get_user_model()

ADMIN_LIST_LIMIT = 10


def get_random_string(size):
    chars = string.ascii_lowercase + string.ascii_uppercase + string.digits
    return ''.join(random.choice(chars) for _ in range(size))


# Admin Login
def LogIn(request):
    if request.method == "POST":
        user = User.objects.filter(email=request.POST.get("username"))
        if not user:
            messages.info(request, "Invalid Login credentials")
            return HttpResponseRedirect("/admin/")
        user = user[0]

        if not user.check_password(request.POST.get("password")):
            messages.info(request, "Invalid Login credentials")
            return HttpResponseRedirect("/admin/")

        if not user.is_superuser:
            messages.info(request, "You dont have permission to access admin panel")
            return HttpResponseRedirect("/admin/")

        login(request, user)
        messages.info(request, "Login Successfully")
        return HttpResponseRedirect(reverse("admin_dashboard:dashboard"))
    return render(request, "login.html")


def logout_user(request):
    logout(request)
    messages.info(request, "Logout Successfully")
    return HttpResponseRedirect('/admin/')


def data_pagination(request, query_set):
    paginator = Paginator(query_set, ADMIN_LIST_LIMIT)
    page = request.GET.get('page', '1')
    try:
        _paginated_data = paginator.page(page)
    except PageNotAnInteger:
        _paginated_data = paginator.page(1)
    except EmptyPage:
        _paginated_data = paginator.page(paginator.num_pages)
    return _paginated_data, page, (ADMIN_LIST_LIMIT * int(page)) - ADMIN_LIST_LIMIT


@user_passes_test(lambda u: u.is_superuser, login_url='/')
def dashboard(request):
    all_users = User.objects.all().exclude(id=request.user.id)
    dt = {
        "active_users": all_users.filter(is_active=True).count(),
        "total_users": all_users.count(),
        "inactive_users": all_users.filter(is_active=False).count(),
    }
    return render(request, 'admin_dashboard.html', dt)


@user_passes_test(lambda u: u.is_superuser, login_url='/')
def users_listing(request):
    users = User.objects.order_by("-id").exclude(id=request.user.id)

    search, is_active, role, user_type, platform = request.GET.get("search", ""), request.GET.get("is_active",
                                                                                                  "None"), request.GET.get(
        "role", "None"), request.GET.get("user_type", "None"), request.GET.get("platform", "None")

    if search and search != 'None':
        users = users.filter(
            Q(email__icontains=search) |
            Q(email=search)
        )
    if is_active and is_active != 'None':
        if is_active == 'yes':
            users = users.filter(is_active=True)
        else:
            users = users.filter(is_active=False)

    if role and role != "None":
        users = users.filter(role=role)
    if user_type and user_type != "None":
        users = users.filter(user_type=user_type)
    if platform and platform != "None":
        users = users.filter(login_type=platform)

    _paginated_data, page, limit_counts = data_pagination(request, users)
    dt = {
        "users": _paginated_data,
        "page": page,
        "search": search,
        "is_active": is_active,
        "role": role,
        "user_type": user_type,
        "platform": platform,
        "params": "search={}&is_active={}&platform={}".format(search, is_active, role),
        "limit_counts": limit_counts,
    }
    return render(request, "user_lists.html", dt)


# User view,add and update
@user_passes_test(lambda u: u.is_superuser, login_url='/')
def add_update_user(request, id, mode):
    if mode == "new":
        user = User()
    else:
        user = User.objects.get(id=id)

    if request.method == "POST":
        password = None
        if user.email != request.POST.get("email"):
            if User.objects.filter(email=request.POST.get("email")):
                messages.info(request, "User with this email already exist.")
                return HttpResponseRedirect(reverse('admin_dashboard:all_users'))
            else:
                pass
        for key, val in request.POST.items():
            if key not in ["csrfmiddlewaretoken"]:
                setattr(user, key, val)

        if mode == "new":
            password = get_random_string(10)
            user.is_one_time_login = True
            user.set_password(password)  # change to random alphanumeric password.
            messages.info(request, "Successfully save a new-user")
        else:
            messages.info(request, "Successfully update a '{}' user".format(user.email))
        if request.POST.get("is_active") == "on":
            user.is_active = True
        else:
            user.is_active = False
        if request.POST.get("is_pd_distance") == "on":
            user.is_pd_distance = True
        else:
            user.is_pd_distance = False
        if request.POST.get("is_reading_distance") == "on":
            user.is_reading_distance = True
        else:
            user.is_reading_distance = False
        if request.POST.get("is_f_meter") == "on":
            user.is_f_meter = True
        else:
            user.is_f_meter = False
        user.save()

        if mode == "new":
            try:
                message = "Your email '{}' and password '{}' .".format(user.email, password)
                template = render_to_string("user_addingbyadmin.html", {"message": message})
                send_mail(
                    "Zukti Inovations adding you as user", "",
                    settings.EMAIL_FROM_USER, [user.email],
                    html_message=template,
                    fail_silently=False
                )
            except Exception as e:
                pass
        return HttpResponseRedirect(reverse("admin_dashboard:all_users"))
    return render(request, "user_view.html", {
        "user": user,
        "id": id,
        "url_type": mode,
    })


@user_passes_test(lambda u: u.is_superuser, login_url='/')
def delete_user(request, id):
    User.objects.filter(id=id).delete()
    messages.info(request, "Successfully deleting a user.")
    return HttpResponseRedirect(reverse("admin_dashboard:all_users"))

admin/admin_dashboard/templates/admin_dashboard.html
{% extends "layouts/base.html" %}
{% block title %} Dashboard {% endblock %}
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<style>
    .recent_user img {
        height: 115px;
    }

</style>
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper container-fluid">
                <div class="row">
                    <div class="col-md-4 col-sm-12">
                        <a href="{% url 'admin_dashboard:all_users' %}">
                            <div class="netraul_outer">
                                <div class="left_nature">
                                    <p>Total Users</p>
                                    <h5>{{total_users}}</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <a href="{% url 'admin_dashboard:all_users' %}?is_active=yes">
                            <div class="netraul_outer">
                                <div class="left_nature">
                                    <p>Active users</p>
                                    <h5>{{active_users}}</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <a href="{% url 'admin_dashboard:all_users' %}?is_active=no">
                            <div class="netraul_outer">
                                <div class="left_nature">
                                    <p>Inactive Users</p>
                                    <h5>{{inactive_users}}</h5>
                                </div>
                            </div>
                        </a>
                    </div>
<!--                    <div class="col-md-4 col-sm-12">-->
<!--                        <a href="{% url 'admin_dashboard:all_users' %}?role=employee">-->
<!--                            <div class="netraul_outer">-->
<!--                                <div class="left_nature">-->
<!--                                    <p>Total Employee</p>-->
<!--                                    <h5>{{total_employee}}</h5>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                    </div>-->
<!--                    {% for user in user_type_group %}-->
<!--                    <div class="col-md-4 col-sm-12">-->
<!--                        <a href="{% url 'admin_dashboard:all_users' %}?user_type={{user.user_type}}">-->
<!--                            <div class="netraul_outer">-->
<!--                                <div class="left_nature">-->
<!--                                    <p>Total {{user.user_type}}</p>-->
<!--                                    <h5>{{user.count}}</h5>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                    </div>-->
<!--                    {% endfor %}-->


                </div>
                <div class="row">
                    <div class="col-md-12 col-xm-12 more_user">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

admin/admin_dashboard/templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- link -->
    <link href="{% static 'PowerBI/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'PowerBI/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://kit-pro.fontawesome.com/releases/v5.15.1/css/pro.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Zukti Inovations</title>
</head>
<body>
<section class="login_outer">
    <div class="container">

        <div class="col-lg-6 col-md-12 offset-lg-3">
            <div class="login_inner">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} msg" style="position:absolute;">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                <div class="logo_outer entna_view">
                    <a href="/admin/login/">
                        <img src="{% static 'images/zukti_logo.png' %}" alt="Zukti">
                        <h3>Admin Panel</h3>
                    </a>
                </div>

                <form class="custom_form" action="{% url 'admin_dashboard:login' %}" role="form" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}"/>
                    {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                    <div class="well well-small text-error" style="border: none">{{ error }}</div>
                    {% endfor %}
                    {% endif %}
                    <div class="input_outer4">
                        <input type="text" name="username" maxlength="100" placeholder="johndoe@mail.com"
                               autocapitalize="off"
                               autocorrect="off" class="form-control textinput textInput"
                               id="id_username" required autofocus
                               {% if form.username.value %}value="{{ form.username.value }}" {% endif %}>
                        {% if form.username.errors %}
                        <p class="text-error">
                            {{ form.username.errors|striptags }}
                        </p>
                        {% endif %}
                    </div>
                    <div class="input_outer4">
                        <input type="password" name="password" maxlength="100" autocapitalize="off" autocorrect="off"
                               class="form-control textinput textInput" id="id_password" required>
                        {% if form.password.errors %}
                        <p class="text-error">
                            {{ form.password.errors|striptags }}
                        </p>
                        {% endif %}
                    </div>
                    <div class="loging_outer45">
                        <button type="submit" name="submit" class="btn" style="background-color: #499ca2; color: #fff;"
                                id="submit-id-submit">Log in
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="/static/PowerBI/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript">

$(".msg").fadeOut(2500)


</script>
</body>
</html>

admin/admin_dashboard/templates/user_lists.html
{% extends "layouts/base.html" %}
{% block title %} Dashboard {% endblock %}
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}
<style>
.user_wrapper.recent_user p {
    text-align: center;
    font-size: 18px;
    text-transform: capitalize;
    background: #2196f3;
    color: white;
    font-weight: bold;
    padding: 7px;
    border-radius: 3px;
}
.recent_user img {
    height: 115px;
}
a.add_btn {
    right: 18px;
    position: absolute;
    top: 4px;
    vertical-align: middle;
}
.custom_fot7{
    float: left;
    margin-bottom: 2%;
    padding: 1%;
}
.custom_fot7 .form-control {
    float: left;
    width: auto;
}
.form-control.go_button input {
    right: 43px;
    top: 110px;
}
select.form-select {
    padding: 4px;
    font-weight: 300;
}

</style>
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper container-fluid">
                <div class="row">
                    <div class="Recent-Users col-md-12 col-xm-12">
                        <h5>All Users <a class="btn btn-success add_btn"
                                         href="{% url 'admin_dashboard:user_view_edit' id=0 mode='new' %}">Add User</a>
                        </h5>
                    </div>
                    <form action="{% url 'admin_dashboard:all_users' %}" class="custom_fot7" method="get">
                        {% csrf_token %}
                        <div class="form-control custom_input9">
                            <input name="search" placeholder="Enter text to search..." type="text"
                                   value="{{search}}">
                        </div>
                        <div class="form-control custom_input9">
                            <select class="form-select form-select-sm" name="is_active">
                                <option value="">Select ActiveUser</option>
                                <option {% if is_active == "yes"%} selected="selected"{% endif %} value="yes">Active User</option>
                                <option {% if is_active == "no"%} selected="selected"{% endif %} value="no">Inactive User</option>
                            </select>
                        </div>

                        <div class="form-control custom_input9">
                            <select class="form-select form-select-sm" name="platform">
                                <option value="">Select Platform</option>
                                <option {% if platform == "normal"%} selected="selected"{% endif %} value="normal">No platform</option>
                                <option {% if platform == "google"%} selected="selected"{% endif %} value="google">Google</option>
                                <option {% if platform == "facebook"%} selected="selected"{% endif %} value="facebook">Facebook</option>
                            </select>
                        </div>

                        <div class="form-control go_button">
                            <input type="submit" value="Go">
                        </div>
                    </form>
                    <div class="Recent-Users col-md-12 col-xm-12">
                        <div class="table-responsive">
                            {% if users %}
                            <table class="table">
                                <thead class="blck7">
                                <th>S.No</th>
                                <th>Email</th>
                                <td></td>
                                </thead>
                                {% for user in users %}
                                <tr>
                                    <td>{{forloop.counter|add:limit_counts}}</td>
                                    <td>{{user.email}}</td>
                                    <td class="both_icon">
                                        <a class="btn btn-primary edit_outer"
                                           href="{% url 'admin_dashboard:user_view_edit' id=user.id mode='edit' %}">
                                            <i class="material-icons">edit</i></a>
                                        <a class="btn btn-primary delete_outer"
                                           href="{% url 'admin_dashboard:delete_user' user.id%}">
                                            <i class="material-icons">close</i></a>
                                    </td>

                                </tr>
                                {% endfor %}
                            </table>
                            {% else %}
                            <p>No User Found.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% include "includes/pagination.html" with page_obj=users %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

admin/admin_dashboard/templates/user_view.html
{% extends "layouts/base.html" %}
{% block title %} UI Forms {% endblock %}
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper container-fluid">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <div class="col-md-12 col-xm-12">
                        <div class="custom_edit6">
                            <h2 class="heading custom_heding7">Profile View</h2>
                        </div>
                        <form action="{% url 'admin_dashboard:user_view_edit' id=id mode=url_type%}" class="custom_actibe9"
                              enctype="multipart/form-data" method="post">
                            {%csrf_token%}
                            {% if user.image %}
                                <div class="form-group row">
                                    <div class="col-lg-12">
                                            <img src="{{user.image.url}}">
                                    </div>
                                </div>
                            {% endif %}
                            <div class="form-group row">
                                <div class="col-lg-6">
                                    <label class="full_nam4">First Name</label>
                                    <div class="staic_outer">
                                        <input name="first_name" required type="text" value="{{user.first_name}}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <label class="full_nam4">Last Name</label>
                                    <div class="staic_outer">
                                        <input name="last_name" required type="text" value="{{user.last_name}}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <label class="full_nam4">Email</label>
                                    <div class="staic_outer">
                                        <input name="email" required type="email" value="{{user.email}}">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-lg-6">
                                    <div class="input8">
                                        <span class="custom_acy7">Is PD Distance</span>
                                        <input type="checkbox" class="custon_avt" name="is_pd_distance" {% if user.is_pd_distance %} checked="checked" {% endif %}>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="input8">
                                        <span class="custom_acy7">Is Reading Distance</span>
                                        <input type="checkbox" class="custon_avt" name="is_reading_distance" {% if user.is_reading_distance %} checked="checked" {% endif %}>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="input8">
                                        <span class="custom_acy7">Is Ft Meter</span>
                                        <input type="checkbox" class="custon_avt" name="is_f_meter" {% if user.is_f_meter %} checked="checked" {% endif %}>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="input8">
                                        <span class="custom_acy7">User Active</span>
                                        <input checked="checked" class="custon_avt" name="is_active" {% if user.is_active %} type="checkbox" {% endif %}>
                                    </div>
                                </div>
                            </div>
<!--                            <div class="form-group row">-->
<!--                                <div class="col-lg-6">-->
<!--                                    <label class="full_nam4">User Role</label>-->
<!--                                    <div class="staic_outer">-->
<!--                                        <select class="form-select" name="role">-->
<!--                                            <option {% if user.role == "normal" %} selected="selected" {% endif %}value="normal">Normal</option>-->
<!--                                            <option {% if user.role == "employee" %} selected="selected" {% endif %}value="employee">Employee</option>-->
<!--                                            <option {% if user.role == "broker" %} selected="selected" {% endif %}value="broker">Broker</option>-->
<!--                                        </select>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
                            <div class="form-group image row">
                                {% if user.image %}
                                <img src="{{user.image.url}}">
                                {% endif %}
                            </div>
                            <div class="form-group row">
                                <div class="col-lg-6">
                                    <button class="btn btn-dark" type="submit">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock  %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>
    var role="{{user.role}}"
    if (role == "broker"){
        $("div.broker").find(".broker_data").show()
        $("div.broker").find(".broker_data").find("input").attr("required","required")
    }else{
        $("div.broker").find(".broker_data").hide()
        $("div.broker").find(".broker_data").find("input").removeAttr("required")
    }
    $('select[name="role"]').change(function(e){
        if($(this).val()=="broker"){
            $("div.broker").find(".broker_data").show()
            $("div.broker").find(".broker_data").find("input").attr("required","required")
        }else{
            $("div.broker").find(".broker_data").hide()
            $("div.broker").find(".broker_data").find("input").removeAttr("required")
        }
    })


</script>
{% endblock %}