admin/admin_dashboard/urls.py
from django.urls import path

from .views import *

app_name = "admin_dashboard"

urlpatterns = [
    path('', LogIn, name="login"),
    path('logout/', logout_user, name="logout_user"),
    path('dashboard/', dashboard, name="dashboard"),
    path('users/', users_listing, name="all_users"),
    path('users/<int:id>/<str:mode>/', add_update_user, name="user_view_edit"),
    path('users/delete/<int:id>/', delete_user, name="delete_user")
]

admin/admin_panel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

admin.site.site_header = 'Zukti Inovations'
admin.site.site_title = 'Zukti Inovations'
admin.site.site_url = "/admin/dashboard"
admin.site.index_title = 'Zukti Inovations'
admin.empty_value_display = '**Empty**'

urlpatterns = [
    path('backend/', admin.site.urls),
    path("admin/", include("admin_dashboard.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += (
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    )

admin/admin_dashboard/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .manager import UserManager


# Create your models here.

class Users(AbstractUser):

    username = None
    email = models.EmailField("email address", blank=True,unique=True)
    social_id = models.CharField(max_length=500, null=True, blank=True)
    login_type = models.CharField(default="normal", max_length=255, choices=(
        ("normal", "Normal"), ("google", "Google"), ("facebook", "Facebook")
    ))
    is_one_time_login = models.BooleanField(default=False)
    is_pd_distance = models.BooleanField(default=False)
    is_reading_distance = models.BooleanField(default=False)
    is_f_meter = models.BooleanField(default=False)
    objects = UserManager()
    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["first_name", "last_name"]
    image = models.ImageField(null=True, blank=True)

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

admin/admin_dashboard/views.py
import random
import string
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import user_passes_test
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse

User = get_user_model()

ADMIN_LIST_LIMIT = 10


def get_random_string(size):
    chars = string.ascii_lowercase + string.ascii_uppercase + string.digits
    return ''.join(random.choice(chars) for _ in range(size))


# Admin Login
def LogIn(request):
    if request.method == "POST":
        user = User.objects.filter(email=request.POST.get("username"))
        if not user:
            messages.info(request, "Invalid Login credentials")
            return HttpResponseRedirect("/admin/")
        user = user[0]

        if not user.check_password(request.POST.get("password")):
            messages.info(request, "Invalid Login credentials")
            return HttpResponseRedirect("/admin/")

        if not user.is_superuser:
            messages.info(request, "You dont have permission to access admin panel")
            return HttpResponseRedirect("/admin/")

        login(request, user)
        messages.info(request, "Login Successfully")
        return HttpResponseRedirect(reverse("admin_dashboard:dashboard"))
    return render(request, "login.html")


def logout_user(request):
    logout(request)
    messages.info(request, "Logout Successfully")
    return HttpResponseRedirect('/admin/')


def data_pagination(request, query_set):
    paginator = Paginator(query_set, ADMIN_LIST_LIMIT)
    page = request.GET.get('page', '1')
    try:
        _paginated_data = paginator.page(page)
    except PageNotAnInteger:
        _paginated_data = paginator.page(1)
    except EmptyPage:
        _paginated_data = paginator.page(paginator.num_pages)
    return _paginated_data, page, (ADMIN_LIST_LIMIT * int(page)) - ADMIN_LIST_LIMIT


@user_passes_test(lambda u: u.is_superuser, login_url='/')
def dashboard(request):
    all_users = User.objects.all().exclude(id=request.user.id)
    dt = {
        "active_users": all_users.filter(is_active=True).count(),
        "total_users": all_users.count(),
        "inactive_users": all_users.filter(is_active=False).count(),
    }
    return render(request, 'admin_dashboard.html', dt)


@user_passes_test(lambda u: u.is_superuser, login_url='/')
def users_listing(request):
    users = User.objects.order_by("-id").exclude(id=request.user.id)

    search, is_active, role, user_type, platform = request.GET.get("search", ""), request.GET.get("is_active",
                                                                                                  "None"), request.GET.get(
        "role", "None"), request.GET.get("user_type", "None"), request.GET.get("platform", "None")

    if search and search != 'None':
        users = users.filter(
            Q(email__icontains=search) |
            Q(email=search)
        )
    if is_active and is_active != 'None':
        if is_active == 'yes':
            users = users.filter(is_active=True)
        else:
            users = users.filter(is_active=False)

    if role and role != "None":
        users = users.filter(role=role)
    if user_type and user_type != "None":
        users = users.filter(user_type=user_type)
    if platform and platform != "None":
        users = users.filter(login_type=platform)

    _paginated_data, page, limit_counts = data_pagination(request, users)
    dt = {
        "users": _paginated_data,
        "page": page,
        "search": search,
        "is_active": is_active,
        "role": role,
        "user_type": user_type,
        "platform": platform,
        "params": "search={}&is_active={}&platform={}".format(search, is_active, role),
        "limit_counts": limit_counts,
    }
    return render(request, "user_lists.html", dt)


# User view,add and update
@user_passes_test(lambda u: u.is_superuser, login_url='/')
def add_update_user(request, id, mode):
    if mode == "new":
        user = User()
    else:
        user = User.objects.get(id=id)

    if request.method == "POST":
        password = None
        if user.email != request.POST.get("email"):
            if User.objects.filter(email=request.POST.get("email")):
                messages.info(request, "User with this email already exist.")
                return HttpResponseRedirect(reverse('admin_dashboard:all_users'))
            else:
                pass
        for key, val in request.POST.items():
            if key not in ["csrfmiddlewaretoken"]:
                setattr(user, key, val)

        if mode == "new":
            password = get_random_string(10)
            user.is_one_time_login = True
            user.set_password(password)  # change to random alphanumeric password.
            messages.info(request, "Successfully save a new-user")
        else:
            messages.info(request, "Successfully update a '{}' user".format(user.email))
        if request.POST.get("is_active") == "on":
            user.is_active = True
        else:
            user.is_active = False
        if request.POST.get("is_pd_distance") == "on":
            user.is_pd_distance = True
        else:
            user.is_pd_distance = False
        if request.POST.get("is_reading_distance") == "on":
            user.is_reading_distance = True
        else:
            user.is_reading_distance = False
        if request.POST.get("is_f_meter") == "on":
            user.is_f_meter = True
        else:
            user.is_f_meter = False
        user.save()

        if mode == "new":
            try:
                message = "Your email '{}' and password '{}' .".format(user.email, password)
                template = render_to_string("user_addingbyadmin.html", {"message": message})
                send_mail(
                    "Zukti Inovations adding you as user", "",
                    settings.EMAIL_FROM_USER, [user.email],
                    html_message=template,
                    fail_silently=False
                )
            except Exception as e:
                pass
        return HttpResponseRedirect(reverse("admin_dashboard:all_users"))
    return render(request, "user_view.html", {
        "user": user,
        "id": id,
        "url_type": mode,
    })


@user_passes_test(lambda u: u.is_superuser, login_url='/')
def delete_user(request, id):
    User.objects.filter(id=id).delete()
    messages.info(request, "Successfully deleting a user.")
    return HttpResponseRedirect(reverse("admin_dashboard:all_users"))

admin/admin_dashboard/templates/includes/navigation.html
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <span class="b-title">Zukti Inovation</span>
            <a class="mobile-menu" href="javascript:" id="mobile-collapse"><span></span></a>
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li class="nav-item" data-username="dashboard Default Ecommerce CRM Analytics Crypto Project">
                    <a class="nav-link " href="/backend/"><span class="pcoded-micon"><i class="fa fa-database"></i>
                    </span><span class="pcoded-mtext">Developer Admin</span></a>
                </li>
                <li class="nav-item" data-username="dashboard Default Ecommerce CRM Analytics Crypto Project">
                    <a class="nav-link " href="{% url 'admin_dashboard:dashboard'%}"><span class="pcoded-micon"><i
                            class="feather icon-home"></i></span>
                        <span class="pcoded-mtext">Home</span></a>
                </li>
                <li class="nav-item" data-username="dashboard Default Ecommerce CRM Analytics Crypto Project">
                    <a class="nav-link " href="{% url 'admin_dashboard:all_users'%}"><span class="pcoded-micon"><i
                            aria-hidden="true" class="fa fa-users"></i>
                    </span><span class="pcoded-mtext">Users</span></a>
                </li>


                <li class="nav-item" data-username="Disabled Menu">
                    <a class="nav-link" href="{% url 'admin_dashboard:logout_user'%}">
                            <span class="pcoded-micon">
                                <i class="feather icon-power"></i>
                            </span>
                        <span class="pcoded-mtext">Logout - [ {{ request.user.email }} ]</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

admin/admin_dashboard/templates/includes/pagination.html
{% if page_obj.has_other_pages %}
<div class="row">
    <div class="col-md-12 col-xm-12 more_user">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item left_arrow">
                    <a aria-label="Previous" class="page-link"
                       href="?page=1{% if sort_by %}&sort_by={{sort_by}}{% endif %}">
                        <i aria-hidden="true" class="fa fa-angle-double-left"></i>
                    </a>
                </li>
                <li class="page-item left_arrow">
                    <a aria-label="Previous"
                       class="page-link"
                       href="?page={{page_obj.number|add:'-1'}}{% if sort_by %}&sort_by={{sort_by}}{% endif %}">
                        <i aria-hidden="true" class="fa fa-angle-left"></i>
                    </a>
                </li>
                {% endif %}

                {% for n in page_obj.paginator.page_range %}
                {% if page_obj.number == n %}
                <li class="page-item active">
                    <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                </li>
                {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link"
                                         href="?page={{ n }}{% if sort_by %}&sort_by={{sort_by}}{% endif %}">{{ n }}</a>
                </li>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item right_arrow">
                    <a aria-label="Next"
                       class="page-link"
                       href="?page={{page_obj.number|add:'1'}}{% if sort_by %}&sort_by={{sort_by}}{% endif %}">
                        <i aria-hidden="true" class="fa fa-angle-right"></i>
                    </a>
                </li>
                <li class="page-item right_arrow">
                    <a aria-label="Next"
                       class="page-link"
                       href="?page={{ page_obj.paginator.num_pages }}{% if sort_by %}&sort_by={{sort_by}}{% endif %}">
                        <i aria-hidden="true" class="fa fa-angle-double-right"></i>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endif %}

admin/admin_dashboard/templates/includes/scripts.html
<!-- Required Js -->
<script src="/static/PowerBI/js/vendor-all.min.js"></script>
<script src="/static/PowerBI/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/PowerBI/js/pcoded.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript">
$( ".dropdown-submenu" ).click(function() {
    $("ul.pcoded-submenu").toggle();
});

$(".msg").fadeOut(2500)
{% if request.resolver_match.url_name not in "review_listing" %}
    $('a.delete_outer').click(function(e){
        if(!confirm("Are you sure you want to delete this. ?")){
            e.preventDefault()
        }
    })
{% endif %}

</script>